"""lembretes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 20:22:03.471805
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminded_at', app.db.UTCDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('reminded_at')

    # ### end Alembic commands ###
