"""resumo do dia

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 21:54:54.574975
"""
from alembic import op
import sqlalchemy as sa
import app.db


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_digest_on', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_digest_on')

    # ### end Alembic commands ###
